bump proc-macro-crate versions
near/borsh-rs pull request #149
Opened 2023-06-09 21:07 UTC by iho

2023-06-12 18:37 UTC, frol requested changes

2023-06-12 18:37 UTC, frol commented on borsh-derive-internal/src/attribute_helpers.rs
> +        > 0
https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.any

```suggestion
        .any(|attr| attr.path().is_ident("borsh_skip"))
```

2023-06-12 18:37 UTC, frol commented on borsh-derive/Cargo.toml
> +syn = { version = "2.0.18", features = ["full", "fold"] }
Unless you explicitly need at least a 2.0.18 version, use `2` instead to let other dependencies prefer some specific version and thus avoid duplication of the syn crate in the dependencies tree.

2023-06-12 18:37 UTC, frol commented on borsh-derive/Cargo.toml
> +proc-macro-crate = "1.3.1"
Same here, consider using `1` as a version.

2023-06-13 21:05 UTC, iho commented on borsh-derive-internal/src/attribute_helpers.rs
> +    let mut res = None;
I don't know the way of returning from outer function from closure. It's recommended way of using `parse_nested_meta`: having local variables that closure mutates.

2023-06-15 07:56 UTC, frol commented on borsh-derive-internal/src/attribute_helpers.rs
> +    let mut res = None;
I suggest to move this line into the `for` -> `if` block, and return after the `let _ = ...` line.

```rust
for {
    if {
        let res = None;
        let _ = ...;
        return res;
    }
}
None
```

2023-06-15 10:47 UTC, frol approved these changes

2023-06-15 10:47 UTC, merged