Implement BorshSerialize/BoshDeserialize for interior mutability stdl…
near/borsh-rs pull request #265
Opened 2023-12-07 03:31 UTC by Fuuzetsu

…ib types

It's basically the same as the serde implementations from 5 years ago https://github.com/serde-rs/serde/pull/882 .

2023-12-07 17:26 UTC, dj8yfo requested changes

2023-12-07 17:26 UTC, dj8yfo commented on borsh/src/de/mod.rs
> +
add trivial implementations of `BorshSchema` for `Cell<T>` and `RefCell<T>`

2023-12-07 17:26 UTC, dj8yfo commented on borsh/src/de/mod.rs
> +
add a test file `borsh/tests/test_cells.rs` with roundtrip tests , and `de_errors` and `schema` modules (with at least 1 test each), similar to https://github.com/near/borsh-rs/blob/master/borsh/tests/test_ascii_strings.rs

2024-02-27 17:48 UTC, dj8yfo commented on borsh/src/ser/mod.rs
> +    }
create a test for `try_borrow` error in `mod de_errors` module of the newly added `borsh/tests/test_cells.rs` file

2024-02-27 22:32 UTC, dj8yfo approved these changes

2024-02-27 22:33 UTC, merged

2024-02-27 23:40 UTC, Fuuzetsu commented
Thank you for getting this through. Sorry, I didn't have the time allocation to finish it up...