feat: add `alloc` feature
near/borsh-rs pull request #56
Opened 2021-12-17 13:59 UTC by pmnoxx

Rust is built around the concept of “zero cost abstraction”.

It's best not to hide extra allocation costs. I see, that by default there is an implementation available for `HashSet` and `HashMap`. It's a good idea to put it behind `alloc` feature.

In order not to break backwards compatibility, I added it to `default_features`.

2021-12-17 14:16 UTC, matklad requested changes
borsh already supports `no_std`, and this feature works correctly. On no-std, HasMap and HashSet are hashbrown variations. This itself is somewhat questionable design descisions though. 


Note that `HashMap` isn't actually a part of `alloc` crate, as it uses access to randomness, which is not a part of alloc.

2021-12-17 14:16 UTC, matklad commented on borsh/src/schema.rs
> +    pub definitions: Vec<(Declaration, Definition)>,
This changes a public API, this shouldn't be done lightly. See https://github.com/near/borsh-rs/issues/51 for the context on things which *could* be better, but which we can't *just* do, as that'll break the world.

2021-12-17 15:10 UTC, closed without merging

2021-12-17 16:20 UTC, pmnoxx commented
@matklad My intention was to add a feature `use_alloc`. Similar to what itertools has: https://docs.rs/crate/itertools/latest/features
They guard with that feature, all functions that have hidden allocs inside, like `.sort()`.

2021-12-20 07:24 UTC, pmnoxx commented
Btw, 

> borsh already supports `no_std`, and this feature works correctly. On no-std, HasMap and HashSet are hashbrown variations. This itself is somewhat questionable design descisions though.
> 
> Note that `HashMap` isn't actually a part of `alloc` crate, as it uses access to randomness, which is not a part of alloc.

FYI, `borsh` can't be compiled without `std`.

```shell
> cargo build --no-default-features

error: cannot find macro `vec` in this scope
   --> borsh/src/de/mod.rs:283:30
    |
283 |             let mut result = vec![T::deserialize(buf)?];
    |                              ^^^
    |
    = note: consider importing one of these items:
            alloc::vec
            crate::maybestd::vec

error: could not compile `borsh` due to previous error
```