Allow not adding the where clause to avoid triggering overflow
near/borsh-rs pull request #96
Opened 2022-07-27 02:03 UTC by Arrowana

# Problem

```rust
#[derive(BorshSerialize, BorshDeserialize)]
enum A {
    B,
    C {
        d: Vec<A>,
    },
}
```

gives `overflow evaluating the requirement A: BorshDeserialize` or BorshSerialize

# Idea

Allow skipping adding to the where clause with an attribute to allow edge cases to function.

I am told this could help https://github.com/rust-lang/rust/issues/48214 but there is currently no way to achieve the same effect "working for recursive data structure" by determining automatically which where clause to add in the proc_macro

# Related issues
https://github.com/near/borsh-rs/issues/7

2022-07-27 08:12 UTC, frol requested changes
Please, add tests

2022-07-27 10:31 UTC, Arrowana commented
> Please, add tests

Sorry, i did have the file locally but forgot to add it.

Please note that I am waiting for your agreement on the broad feature before I'll add it to other types.

2022-07-27 12:16 UTC, frol commented
@Arrowana The reason I asked for the test is to see how this is expected to be used.

Reading https://github.com/near/borsh-rs/issues/7#issuecomment-765582816:

> serde, can handle this case, btw

I wonder how they achieved that and whether it is possible to do here, so we don't need to have this attribute.

2022-07-27 12:20 UTC, Arrowana commented
> @Arrowana The reason I asked for the test is to see how this is expected to be used.
> 
> Reading [#7 (comment)](https://github.com/near/borsh-rs/issues/7#issuecomment-765582816):
> 
> > serde, can handle this case, btw
> 
> I wonder how they achieved that and whether it is possible to do here, so we don't need to have this attribute.

Looked at this user repositories i found this https://github.com/near/borsh-rs/pull/96#issuecomment-1196652786
`MachineValue` is recursive

This is also my current workaround, manual trait implementation, just seems to be a lot of redo.

2022-07-27 12:53 UTC, austinabell commented
> I would much prefer a solution that doesn't require the attribute but i just don't know how or if it is feasible at all.

It is possible, serde handles it. It's definitely more of an extensive process which I had started previously but somewhat abandoned since I didn't have the bandwidth.

2022-11-10 13:55 UTC, vitruvvius commented
lgtm - lets commit

2023-01-27 11:11 UTC, frol commented
I think this PR is stalled and is not required anymore, so I am closing it.

2023-01-27 11:11 UTC, closed without merging